### ISSUE TITLE
Flatten PDF Form

### ISSUE THREAD

**Issue by webonix** [MitrahSoft/lucee-cfpdfform#2]
looks like version 2 of pdfbox has ability to flatten
    https://pdfbox.apache.org/docs/2.0.0-SNAPSHOT/javadocs/org/apache/pdfbox/pdmodel/interactive/form/PDAcroForm.html#flatten()

I will see if I can get some time tomorrow to poke around

**Comment by cfmitrah** [comment]
Merged 8840eea1b317acc0e42a126960cb3b406d429fb5 PR by @webonix
