### ISSUE TITLE
Commandbox: expandPath and getTempDirectory

### ISSUE THREAD

**Issue by DiscountDarcy** [MitrahSoft/lucee-cfpdfform#9]
Using this tag on commandbox without a destination attribute will throw the following error:

`/app/root/serverHome/WEB-INF/lucee-web/temp/98707F93-1938-49D8-95958F544F346507.pdf (No such file or directory)`

It appears that the culprit is the use of expandPath() on getTempDirectory() on line 104. I can submit a PR for this but presumably it's like that for a reason - do standard/Tomcat deployments need this?

**Comment by DiscountDarcy** [comment]
Nevermind -- was just passing in the wrong webroot to commandbox. My mistake.

**Comment by DiscountDarcy** [comment]
I take it back, I'm not crazy.

This works and produced:  root/serverHome/WEB-INF/lucee-web/temp/4E514AC9-F310-49DE-8600A013579C59E7.pdf

` writedump(expandPath(gettempDirectory()) & createUUID() & ".pdf");`

This (which is closer to what is on line 107) does not:

`writedump(expandPath("#gettempDirectory()##createUUID()#.pdf"))`

It produced:

/app/root/serverHome/WEB-INF/lucee-web/temp/A998B507-16CF-4ACA-A4ACECE17DEDD9EF.pdf

**Comment by cfmitrah** [comment]
@MordantWastrel PRs are welcome
